// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

// Dependencies
import { Base_Test } from "@test/Base.t.sol";

// Contracts
import { WebAuthnSessionValidator } from "@validators/WebAuthnSessionValidator.sol";

// Libraries
import { WebAuthn } from "solady/utils/WebAuthn.sol";
import { P256VerifierCode } from "@test/utils/P256VerifierCode.sol";

/// @title WebAuthnSessionValidator_Unit_Test
/// @author highskore.eth
/// @notice Per-contract base for the stateless P256/passkey session-verifier suites: deploys the validator,
///         supplies the credential/assertion helpers, and `vm.etch`es the solady P256 verifier so the
///         valid-P256 path can be PROVEN on-chain here. No install — the credential travels in `data` on every
///         call.
/// @dev Foundry under `cancun` has no RIP-7212 precompile, so solady `WebAuthn.verify` falls back to the
///      Solidity verifier at {P256VerifierCode.ADDR}; we etch its real (Base-fetched) runtime there in setUp so
///      `verify` actually runs. The {FIXTURE_*} vector is a genuine low-s WebAuthn assertion over {DIGEST}
///      (from the SDK `signWebAuthn`, software passkey priv 0xa7…a7) — the same producer the browser/bind path
///      uses — so the verify→true path is real, not faked. (This closes the gap the ROOT {WebAuthnValidator}
///      suite leaves open.)
abstract contract WebAuthnSessionValidator_Unit_Test is Base_Test {
    /*//////////////////////////////////////////////////////////////
                               CONSTANTS
    //////////////////////////////////////////////////////////////*/

    /// @dev A structurally valid but unrelated P256 pubkey (no matching private key) — for negative paths.
    bytes32 internal constant PUBKEY_X =
        0x1111111111111111111111111111111111111111111111111111111111111111;
    bytes32 internal constant PUBKEY_Y =
        0x2222222222222222222222222222222222222222222222222222222222222222;

    /// @dev The WebAuthn challenge for every test. The {FIXTURE_SIG} assertion is a real P256 signature over
    ///      exactly this digest (the validator uses `abi.encode(hash)` as the challenge).
    bytes32 internal constant DIGEST = keccak256("daimon.session.webauthn.digest");

    /// @dev A REAL happy-path fixture: pubkey (FIXTURE_X, FIXTURE_Y) + a low-s {WebAuthn.WebAuthnAuth}
    ///      (FIXTURE_SIG = `abi.encode(WebAuthnAuth)`) over {DIGEST} with UP|UV flags set. Generated by the SDK
    ///      `signWebAuthn` (software passkey priv = 0xa7…a7).
    bytes32 internal constant FIXTURE_X =
        0x418b9b63bd211b39c0f97628be371fa2dc1714f9272dd6bc33e1a60f15623983;
    bytes32 internal constant FIXTURE_Y =
        0x72891f6a9194aa9efcb0981159bad37674592302517c59efcd84588b188129e4;
    bytes internal constant FIXTURE_SIG =
        hex"000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000000170000000000000000000000000000000000000000000000000000000000000001255a9289c1c7bd56123b4e61eae916fb6051214c367e91cc1ccc9ea1c04676262a91a9a41bb5c1ff28a0141c5d82307c8c3bdf74d2cbc44e5e997381cb80eab700000000000000000000000000000000000000000000000000000000000000258648792706d23160285f8b840f3bf64b0f7eaeebf019e01f921eaf56ec78a8e6050000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000857b2274797065223a22776562617574686e2e676574222c226368616c6c656e6765223a224b6f51346a324a306c6e74365448662d774366334e354977474b766b6a7a4d7a775649394d674943364f49222c226f726967696e223a2268747470733a2f2f6461696d6f6e2e6c6f63616c222c2263726f73734f726967696e223a66616c73657d000000000000000000000000000000000000000000000000000000";

    /*//////////////////////////////////////////////////////////////
                                STATE
    //////////////////////////////////////////////////////////////*/

    WebAuthnSessionValidator internal validator;

    /*//////////////////////////////////////////////////////////////
                                SETUP
    //////////////////////////////////////////////////////////////*/

    function setUp() public virtual {
        validator = new WebAuthnSessionValidator();
        // Make solady's P256 fallback verifier available locally (no RIP-7212 precompile under cancun).
        vm.etch(P256VerifierCode.ADDR, P256VerifierCode.CODE);
    }

    /*//////////////////////////////////////////////////////////////
                               HELPERS
    //////////////////////////////////////////////////////////////*/

    /// @dev The session credential blob: `abi.encode(x, y, requireUV)`.
    function _cred(bytes32 x, bytes32 y, bool requireUV) internal pure returns (bytes memory) {
        return abi.encode(x, y, requireUV);
    }

    /// @dev A structurally well-formed but cryptographically invalid {WebAuthn.WebAuthnAuth} blob — it decodes
    ///      cleanly (no decode revert) but cannot pass verification.
    function _malformedAuth() internal pure returns (bytes memory) {
        WebAuthn.WebAuthnAuth memory auth = WebAuthn.WebAuthnAuth({
            authenticatorData: hex"",
            clientDataJSON: "",
            challengeIndex: 0,
            typeIndex: 0,
            r: bytes32(0),
            s: bytes32(0)
        });
        return abi.encode(auth);
    }
}
